services:
  app:
    image: ghcr.io/jrc-brasil/digital_service_report_api:${IMAGE_TAG:-staging}
    container_name: 'service_report_api'
    restart: 'unless-stopped'
    env_file: .env
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      LETSENCRYPT_HOST: '${VIRTUAL_HOST}'
      VIRTUAL_PORT: '${API_PORT}'
    command: 'node ./dist/server.js'
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: ${NGINX_NETWORK_NAME}
